### ISSUE TITLE
Support for Fields with TimeOfDay or Duration Format in Generated Models

### ISSUE THREAD

**Issue by mortadha1144** [masreplay/api_spec_to_dart#25]
## 🐞 Bug: Duration Fields Using TimeOfDay Cause Undefined Class Error

**Package:** swagger_to_dart

### Description

When the OpenAPI schema includes a field with `type: string` and `format: duration`, the generated Dart model assigns it a `TimeOfDay` type, but without importing `TimeOfDay` or handling its Flutter-specific nature. This causes a Dart compile-time error.

### Example Schema

```yaml
components:
  schemas:
    Schedule:
      type: object
      properties:
        start_time:
          type: string
          format: duration
```

### Actual Behavior
The generator produces:

```final TimeOfDay start_time;```

"Error: Undefined class 'TimeOfDay'."

### Suggested Solutions
If TimeOfDay is used:
 - Automatically import package:flutter/material.dart
 -  Generate a TimeOfDay JSON converter to handle serialization/deserialization

### Benefit

- Prevents Dart compilation errors
- Enables native handling of time-only fields in Flutter apps
- Reduces need for post-generation manual edits

Thanks again for maintaining and improving this great package!

---

Let me know if you’d like me to also mention `DurationConverter` as an alternative.
