### ISSUE TITLE
Header not ignored

### ISSUE THREAD

**Issue by harmjanr** [masreplay/api_spec_to_dart#44]
I added the config below to my swagger_to_dart.yaml, to ignore the header X-Client-Platform:
```
  skipped_parameters:
    - X-Client-Platform
```

The generated client still does have the X-Client-Platform param as a required field:
```
  Future<HttpResponse<List<Avatar>>> getAvatars({
    @Header("X-Client-Platform") required Platform? xMinusClientMinusPlatform,
```

Did I configure it wrong, or is there anything else I can do to ignore this header?

**Comment by harmjanr** [comment]
Found it, the skipped_parameters should be within the api_client property. Full example:

```yml
swagger_to_dart:
  url: https://myurl.json
  input_directory: schema/swagger.json
  output_directory: lib/api
  model:
    support_generic_arguments: true
    union_class_fallback_name: fallback
    enum_fallback_type: first
  api_client_class_name: ApiClient
  imports:
  - import 'package:dio/dio.dart';
  api_client:
    base_api_client_class_name: BaseApiClient
    use_class_for_query_parameters: true
    skipped_parameters:
      - X-Client-Platform


```
